# Generated by Django 4.0.4 on 2022-04-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Product_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Product_Type', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=300)),
                ('Brand', models.SlugField(max_length=20)),
                ('ProductImage', models.ImageField(upload_to='')),
            ],
        ),
    ]
