# Generated by Django 4.0.4 on 2022-04-25 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductImage',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_Type',
            field=models.CharField(choices=[('Lungi', 'Lungi'), ('Sharee', 'Sharee'), ('Panjabi', 'Punjabi')], default='UD', max_length=25),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SupplierProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='store.products')),
                ('SupplierID', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewDate', models.DateTimeField(auto_now_add=True)),
                ('Ratings', models.IntegerField()),
                ('Description', models.TextField(max_length=1000)),
                ('CustomerId', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ProductId', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('TransactionID', models.CharField(default='XXX', max_length=50, primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Customer_Id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='store.products')),
                ('TransactionID', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='store.orders')),
            ],
        ),
    ]
