# Generated by Django 4.0.4 on 2022-04-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductImage',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_Type',
            field=models.CharField(choices=[('Lungi', 'Lungi'), ('Sharee', 'Sharee'), ('Panjabi', 'Punjabi')], default='UD', max_length=25),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
