# Generated by Django 4.0.4 on 2022-04-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_products_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Product_Type',
            field=models.CharField(choices=[('Lungi', 'Lungi'), ('Sharee', 'Sharee'), ('Panjabi', 'Punjabi')], default='UD', max_length=25),
        ),
        migrations.AlterField(
            model_name='products',
            name='ProductImage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
