# Generated by Django 4.0.4 on 2022-04-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_useraddressinfo_delete_customer'),
        ('store', '0002_alter_products_productimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
                ('SupplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewDate', models.DateTimeField(auto_now_add=True)),
                ('Ratings', models.IntegerField()),
                ('Description', models.TextField(max_length=1000)),
                ('CustomerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.myuser')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
        ),
    ]
