# Generated by Django 4.0.4 on 2022-05-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orders_amount_orders_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Amount',
        ),
    ]
