# Generated by Django 4.0.4 on 2022-04-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_supplier'),
        ('store', '0003_products_product_type_alter_products_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
                ('SupplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewDate', models.DateTimeField(auto_now_add=True)),
                ('Ratings', models.IntegerField()),
                ('Description', models.TextField(max_length=1000)),
                ('CustomerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('TransactionID', models.CharField(default='20 2022-04-22 23:52:37.815695 20', max_length=50, primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Customer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
                ('TransactionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders')),
            ],
        ),
    ]
