# Generated by Django 4.0.4 on 2022-04-25 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_useraddressinfo_delete_customer'),
        ('store', '0003_supplierproductinfo_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('TransactionID', models.CharField(default='5000 2022-04-25 14:37:53.512940 UD', max_length=50, primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Customer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
                ('TransactionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders')),
            ],
        ),
    ]
