# Generated by Django 4.0.4 on 2022-04-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_supplierproductinfo_review_orders_orderedproductinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='TransactionID',
            field=models.CharField(default='20 2022-04-23 00:41:14.551742 Lungi', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
